### ISSUE TITLE
support for matrices

### ISSUE THREAD

**Issue by BriceonWiley** [RobinHankin/Brobdingnag#5] opened 2020-04-23 09:39 UTC
Good morning. I was wondering if there are any plans to extend the function `as.brob()` to allow coercion into a matrix? Currently, when I try to do so, I get a "no method" error.

`> matrix(as.brob(5))`

**Comment by RobinHankin** [comment] 2020-04-23 19:07
Hello Brice

It's certainly possible in principle (the best way to represent a Brobdingnagian matrix would be as a matrix of doubles and a matrix of logicals for the sign) but the naive implementation would be very slow.  Also, there is no easy way to implement a `solve()`  method other than to coerce to doubles.  What is your application?

**Comment by BriceonWiley** [comment] 2020-04-23 19:20
It is actually for numerical integration and vectorization of the process. I use `hcubature()` from the `cubature` package for my numerical integration and when I vectorize the calculations, the function requires a matrix to be returned. I don't intend to take any inverses or actually perform any matrix calculations. Just, because of the possibility of integrating many times over many parameters, the function wants an object that supports that behavior.

**Comment by RobinHankin** [comment] 2020-04-23 19:56
thinking about it, it wouldn't be too difficult to do Brobdingnagian matrix addition and subtraction and scalar multiplication.  Glubs would be no harder in principle. I'd need a print method too, and `log()` shouldn't be too hard. Could you show me a smple use-case that I could use to test any functionality?

**Comment by BriceonWiley** [comment] 2020-04-23 20:07
For sure! I have to step away from my computer for a little, but as soon as I'm back, I'll send the example.

**Comment by BriceonWiley** [comment] 2020-04-23 20:28
Here you go!
```
f <- function(x) {
  x <- x[1, ]
  matrix(-x^2 + 4, ncol = length(x))
}
cubature::hcubature(f = f, lowerLimit = -2, upperLimit = 2, vectorInterface = TRUE)
```
compared to
```
f.b <- function(x) {
  x <- as.brob(x[1, ])
  matrix(-x^2 + 4, ncol = length(x))
}
cubature::hcubature(f = f.b, lowerLimit = -2, upperLimit = 2, vectorInterface = TRUE)
```

**Comment by RobinHankin** [comment] 2020-04-23 20:50
Hmm.  The problem is in `matrix()` which tries to coerce its argument to a vector:

```
> as.vector(as.brob(1:10))
Error in as.vector(as.brob(1:10)) : 
  no method for coercing this S4 class to a vector
```

Brobs deliberately have no coercion to  numeric vector.  I don't know if this is a showstopper for hcubature.  If there was a `brobmat()` function which could give sensible output for `brobmat(as.brob(1:6),2,3)`, would that work?

**Comment by BriceonWiley** [comment] 2020-04-23 21:09
If it's not too much trouble, I think it'd be worth the try. I use the function a few times a long the way for my main calculation. My biggest issue is losing values because the calculations get too small. If a Brob is able to save a few numbers so that the calculation doesn't shrink too much, I definitely believe it'd be worthwhile!

**Comment by RobinHankin** [comment] 2020-04-23 21:29
OK, I'll create a new branch.  But extraction and replacement methods might be tricky. Ideally one would want idiom like 

```
B <- brobmat(as.brob(1:6),2,3)
B[1,] <- B[2,] + 10
```

but implementing this might not be straightforward, as I know to my cost! The `spray` package has related functionality, and that nearly drove me crazy.

**Comment by BriceonWiley** [comment] 2020-04-23 22:24
Ah ok, well if there's any help that I can be, please let me know! You're doing great work! I've also looked into your `hypgergeo` package as well.

**Comment by RobinHankin** [comment] 2020-04-26 01:09
Brice, after a bit of coding we now have something close to your use-case.  Using the `matrix` branch:

```
library("Brobdingnag")
library("cubature")

f.b <- function(x) {
  x <- as.brob(x[1, ])
 as.matrix( brobmat(-x^2 + 4, ncol = length(x)))
}

print(cubature::hcubature(f = f.b, lowerLimit = -2, upperLimit = 2, vectorInterface = TRUE))
```

I get 

```
$integral
[1] 10.66667

$error
[1] 1.184238e-13

$functionEvaluations
[1] 1

$returnCode
[1] 0

> 
```

It's not quite what you asked for,as I have had to coerce the output back to a double; `hcubature()` needs doubles.  But the calculations are carried out using Brobdingnagian arithmetic.  I have not yet written any documentation at all, as the implementation is subject to change.
 Let me know if this helps!

**Comment by RobinHankin** [comment] 2020-09-27 02:14
closing, as per  commit 3f7d872ce05d0938e9faa194dc2d4a902526cde6 

Brice, let me know if you have any comments or suggestions,  best wishes, Robin

**Closed by RobinHankin** 2020-09-27 02:14 UTC
